name: LaTeX compilation
run-name: ${{ github.actor }} is compiling the PDF
on: [push]
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: paper.tex
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: paper.pdf
      - name: Release PDF file
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: paper.pdf
